FROM node:20-alpine

# Instalar PNPM globalmente
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Copiamos los archivos de raíz necesarios para pnpm y turbo
COPY package.json pnpm-lock.yaml turbo.json ./

# Copiamos las apps y cualquier paquete compartido
COPY apps ./apps
COPY packages ./packages
COPY .env .env

# Instalamos dependencias de todo el monorepo
RUN pnpm install --frozen-lockfile

# Construimos sólo el backend
WORKDIR /app/apps/api

CMD ["pnpm", "dev"]